Chapter.create(id: 1,name: "HTML&CSSに触れてみよう",curriculum_id: 1)
Chapter.create(id: 2,name: "Rubyに触れてみよう",curriculum_id: 1)
Chapter.create(id: 3,name: "Railsに触れてみよう",curriculum_id: 1)
Chapter.create(id: 4,name: "Command Lineに触れてみよう",curriculum_id: 1)
Chapter.create(id: 5,name: "Gitに触れてみよう",curriculum_id: 1)
Chapter.create(id: 6,name: "JavaScriptに触れてみよう",curriculum_id: 1)
Chapter.create(id: 7,name: "SQLに触れてみよう",curriculum_id: 1)
Chapter.create(id: 8,name: "ファイルとディレクトリ",curriculum_id: 2)
Chapter.create(id: 9,name: "ユーザと権限",curriculum_id: 2)
Chapter.create(id: 10,name: "パッケージ管理",curriculum_id: 2)
Chapter.create(id: 11,name: "コマンドとシェルスクリプト",curriculum_id: 2)
Chapter.create(id: 12,name: "Docker",curriculum_id: 2)
Chapter.create(id: 13,name: "I/Oの概念",curriculum_id: 2)
Chapter.create(id: 14,name: "Git",curriculum_id: 2)
Chapter.create(id: 15,name: "GitHubFlowを使おう",curriculum_id: 2)